### ISSUE TITLE
Learning Rust and Deno

### ISSUE THREAD

**Issue by rvalenciano** [iamkevinwolf/learning#4]
My personal goal this 2020 is to learn rust (https://doc.rust-lang.org/book/) and help https://github.com/denoland/deno to get to a better place.

There is a chance that nodejs infrastructure will start moving away from NodeJS and NPM into Deno and descentralized packages.

https://www.youtube.com/watch?v=z6JRlx5NC9E

**Comment by iamkevinwolf** [comment]
Thanks for the recommendation, I have been wanting to learn some rust for a while now.

**Comment by iamkevinwolf** [comment]
@allcontributors please add @rvalenciano for his idea of learning Rust
